# Generated by Django 2.1 on 2020-04-25 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('invest_id', models.AutoField(primary_key=True, serialize=False)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invest_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment',
            },
        ),
    ]
