# Generated by Django 2.1 on 2020-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='no_shares',
            field=models.IntegerField(default=0),
        ),
    ]
